apiVersion: extensions/v1beta1
#apiVersion: apps/v1beta1
#apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 12
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
     containers:
     - name: hello-pod
       image: nigelpoulton/pluralsight-docker-ci:latest
       #image: httpd:latest
       #image: ubuntu:latest
       ports:
       - containerPort: 8080
