apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world

  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30123
    #targetPort: 30123

  #type: LoadBalancer
  type: NodePort
